### ISSUE TITLE
Please consider using Moneta as a cache backend

### ISSUE THREAD

**Issue by minad** [plataformatec/faraday-http-cache#22]
See https://github.com/minad/moneta. This makes it easier to use in projects which don't use rails/activesupport. If you consider switching to Moneta I would be willing to provide a patch.

**Comment by metaskills** [comment]
Thanks for not locking down this issue. I would like to propose that we reconsider this. Moneta has a clean API and zero gem dependencies. It seems reasonable that a gem which exposes a cache object do so in a way that allows someone else to write the adapter. By not including Moneta as a gem dep, you are require people to write small ad-hoc adapters to use the gem without Rails. I know that is not a big deal, but I can see the point. 

Just wanted to make sure this position of not including it is up to date. Thanks in advance!

**Comment by lucasmazza** [comment]
@metaskills I'm still :-1: on adding the `moneta` runtime dependency, specially after the work of removing the explicit AS dependency. But maybe we can do something to support Moneta's API on top of the `read`/`write` protocol we already support [here](https://github.com/plataformatec/faraday-http-cache/blob/master/lib/faraday/http_cache/storage.rb#L163-L165).
