### ISSUE TITLE
Invalidation after Update or Delete

### ISSUE THREAD

**Issue by joshuacronemeyer** [plataformatec/faraday-http-cache#42]
http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.10

Some HTTP methods MUST cause a cache to invalidate an entity: PUT, DELETE, POST. Have you guys considered implementing this part of the spec? I would be happy to work on this, but wouldn't want to do the work if you guys had intentionally skipped it.

**Comment by lucasmazza** [comment]
Implemented at #57.

**Comment by joshuacronemeyer** [comment]
Thanks. Great work!
