### ISSUE TITLE
Cache-Control headers in requests are not honoured 

### ISSUE THREAD

**Issue by KaptajnKold** [plataformatec/faraday-http-cache#52]
It appears from my private testing and from reading the source code that faraday-http-cache does not honour Cache-Control headers in requests. This is unfortunate, as this prevents clients from selectively bypassing the cache. I am aware that you can work around this by appending a cache-busting query parameter to request urls when you want to force revalidation. This however is suboptimal, as it causes the cache(s) to be filled with responses that are never read again, possibly at the expense of those that will be.

**Comment by georgeguimaraes** [comment]
You're right. Cache-Control headers in request are not taken into account. We haven't had this use case yet but we'd be interested in a Pull Request implementing it.

**Comment by KaptajnKold** [comment]
Working on it ;)
