### ISSUE TITLE
Is there a changelog?

### ISSUE THREAD

**Issue by monfresh** [plataformatec/faraday-http-cache#60]
Hi,

Maybe I missed it, but I can't seem to find a changelog here. It would be very helpful to know what changed between each version, especially if there are any breaking changes between 0.4.2 and 1.0.

Thanks!

**Comment by lucasmazza** [comment]
Just pushed a CHANGELOG @ f11816d90dce9a423c9fd8aa012d33603543b7aa. `1.0.1` shouldn't have any breaking changes on top of `0.4.x` series, only if you have been using the deprecated API to pass AS Cache options to the middleware.

:v:

**Comment by monfresh** [comment]
Awesome. Thanks!
