### ISSUE TITLE
Not asking for cached response when, afaik, it should

### ISSUE THREAD

**Issue by jjb** [plataformatec/faraday-http-cache#61]
This client:

```ruby
client = Faraday.new do |builder|
  builder.use :http_cache, shared_cache: false, serializer: Marshal, store: ActiveSupport::Cache::FileStore.new("/tmp/sitemap-cache")
  builder.adapter Faraday.default_adapter
end
```

Is not asking for the cached version of this file:

```
➔ curl --head https://res-2.cloudinary.com/medstro/image/upload/s--JIOrIyZ1--/c_thumb,f_auto,g_face,h_100,q_jpegmini,w_100/v1386214311/user_avatars/1.jpg
HTTP/1.1 200 OK
Access-Control-Allow-Headers: X-Requested-With
Access-Control-Allow-Origin: *
Content-Disposition: inline; filename="1.jpg"
Content-Transfer-Encoding: binary
Content-Type: image/jpeg
ETag: "ed587ecaec998de4c3bc15c1fe665ff5"
Last-Modified: Sat, 28 Feb 2015 17:25:40 GMT
Server: cloudinary
Status: 200 OK
X-Request-Id: 2d30d14a51f42ae4
X-UA-Compatible: IE=Edge,chrome=1
Content-Length: 6253
Cache-Control: public, private, max-age=946634
Expires: Mon, 30 Mar 2015 17:26:11 GMT
Date: Thu, 19 Mar 2015 18:28:57 GMT
Connection: keep-alive
```

The only header it is sending is `"User-Agent"=>"Faraday v0.9.1"`

Am I mistaken or should it be requesting the cached version?

It is successfully writing to the cache.

**Comment by lucasmazza** [comment]
Hey, what do you mean by "requesting the cached version"? Testing locally with `faraday-http-cache` 1.0.1 the client caches the response in the first request and then reuses it in the following requests, since the `max-age` header enables the client to cache the response for some time.

If you execute the following script:

```ruby
require 'faraday'
require 'faraday-http-cache'
require 'logger'

logger = Logger.new($stdout)
logger.formatter = -> (severity, datetime, progname, msg) { "#{msg}\n" }
client = Faraday.new do |builder|
  builder.use :http_cache, shared_cache: false, serializer: Marshal, logger: logger
  builder.adapter Faraday.default_adapter
end

5.times do
  client.get('https://res-2.cloudinary.com/medstro/image/upload/s--JIOrIyZ1--/c_thumb,f_auto,g_face,h_100,q_jpegmini,w_100/v1386214311/user_avatars/1.jpg')
end
```

You will get the following output explaining what happened:

```
$ ruby http_cache_test.rb
HTTP Cache: [GET /medstro/image/upload/s--JIOrIyZ1--/c_thumb,f_auto,g_face,h_100,q_jpegmini,w_100/v1386214311/user_avatars/1.jpg] miss, store
HTTP Cache: [GET /medstro/image/upload/s--JIOrIyZ1--/c_thumb,f_auto,g_face,h_100,q_jpegmini,w_100/v1386214311/user_avatars/1.jpg] fresh
HTTP Cache: [GET /medstro/image/upload/s--JIOrIyZ1--/c_thumb,f_auto,g_face,h_100,q_jpegmini,w_100/v1386214311/user_avatars/1.jpg] fresh
HTTP Cache: [GET /medstro/image/upload/s--JIOrIyZ1--/c_thumb,f_auto,g_face,h_100,q_jpegmini,w_100/v1386214311/user_avatars/1.jpg] fresh
HTTP Cache: [GET /medstro/image/upload/s--JIOrIyZ1--/c_thumb,f_auto,g_face,h_100,q_jpegmini,w_100/v1386214311/user_avatars/1.jpg] fresh
```

**Comment by jjb** [comment]
Wow, thanks for the quick response!

> what do you mean by "requesting the cached version"? 

I meant that the only header it is sending is "User-Agent"=>"Faraday v0.9.1"

I'm going to experiment with your code now and see what the difference is between yours and mine.

**Comment by lucasmazza** [comment]
There isn't any specific header that should be used in this case since we are not doing any cache validation. Only when the cache entry gets stale that the client verifies if the cache is outdated through the `ETag` value.

**Comment by jjb** [comment]
> There isn't any specific header that should be used in this case since we are not doing any cache validation. Only when the cache entry gets stale that the client verifies if the cache is outdated

![image](https://cloud.githubusercontent.com/assets/6097/6738673/f2421580-ce49-11e4-81b5-c5605ff1c9c7.png)

Okay, that's why. It wasn't sending any request at all!

My code does behave properly, I set it up to be analogous to yours and the log is identical. The reason I thought it was not behaving correctly is because I was experimenting in pry and always seeing this `Faraday::Response` object come up, with no headers being sent and a 200 as a response.

![pasted_image_3_19_15__3_18_pm](https://cloud.githubusercontent.com/assets/6097/6738898/758caab2-ce4b-11e4-93cf-c4134a83d37a.png)
