### ISSUE TITLE
Does the cache need to be read twice? (when a write is necessary)

### ISSUE THREAD

**Issue by dwo** [plataformatec/faraday-http-cache#73]
Hi. I have noticed something and wanted to understand better. 

I thought the middleware might limit reads from the cache to 1 per `call`. It seems as though the cost of a fresh entry is 1 cache read, but the cost of a miss or stale entry is 2 cache reads and 1 cache write. I put loggers onto my `Rails.cache` and onto the faraday-http-cache middleware.

```
DEBUG (ActiveSupport::Cache) Cache read: 8be021fb01652c929e4ba5df5f5854dd5419161d
DEBUG (ActiveSupport::Cache) Cache read: 8be021fb01652c929e4ba5df5f5854dd5419161d
DEBUG (ActiveSupport::Cache) Cache write: 8be021fb01652c929e4ba5df5f5854dd5419161d
DEBUG (Faraday::HttpCache) HTTP Cache: [GET /foo/bar] miss, store
```

So I read the code for for the `write` method on `Storage`: https://github.com/plataformatec/faraday-http-cache/blob/v1.1.1/lib/faraday/http_cache/storage.rb#L44-L61

I guess the same key is re-read out of the cache (during `Storage#write`) in order to ensure that if something else has written to the `entries` in between the cache miss (or stale entry) and the backend completing its response (200 or 304), then the new entries are preserved? 
 
Is there a reason that responses in `entries` don't each get their own cache key? Under the current implementation you may end up fetching several responses that you will `reject!` from the cache, but I feel like there is probably a way to get all the factors from `response_matches?` into the cache key, so that you only ever look up single appropriate cached responses. That might also mean that races between things writing to cache keys would be less of a worry (as you wouldn't end up accidentally "un-caching" any other responses, just potentially re-writing one).

Maybe I've misunderstood something, or not expressed myself clearly. Maybe you determined that the cost of doing things this way was low anyway. Let me know what you think.

**Comment by lucasmazza** [comment]
The main reason behind this is indeed the logic for the `response_matches?`, since we can cache multiple responses for the same URI that are matched by different requests (#55). I don't think we would be able the express the logic behind `vary_matches?` entirely with the composition of the cache key, but would be nice to see some spikes on this piece.
