### ISSUE TITLE
Ability to black list certain urls when caching

### ISSUE THREAD

**Issue by tarebyte** [plataformatec/faraday-http-cache#75]
Hi There,

I'm sorry if this was mentioned somewhere and I waltzed right past it. Is there a reasonable way to exclude certain urls from being cached?

**Comment by lucasmazza** [comment]
@tarebyte we don't have a high level API for blacklisting or any sort of configuration, but you can use the HTTP semantics to control how the cache will treat a specific request when necessary:

Passing the `Cache-Control: no-store` header will make the request skip the whole caching mechanism (the middleware won't read or write anything from the cache), and `Cache-Control: no-cache` will ignore any existing caching entries, perform the request and then update the cache with the fresh response (so while this request skipped the cache, the next ones will pick up the same response).

So, in your case with Octokit, I believe it will be just a matter of passing a `headers: { cache_control: '' }` to the client methods for it to use the header and skip/bypass the cache in that API call.

**Comment by tarebyte** [comment]
Awesome, thank you @lucasmazza!
