### ISSUE TITLE
Ignore HTTP headers

### ISSUE THREAD

**Issue by schopenhauer** [plataformatec/faraday-http-cache#76]
Hello,

I would like to know, if there is a way to partially ignore the HTTP headers prior to validation. The pages I'd like to cache have a Cache-Control: no-store tag, whch I am trying to override and cache anyway.

Many thanks.

**Comment by lucasmazza** [comment]
@schopenhauer no, there isn't. If you want to cache requests ignoring the HTTP semantics you should use other solutions like the `FaradayMiddleware::Caching` middleware.
