### ISSUE TITLE
If response is not_modified, why we need to store it again?

### ISSUE THREAD

**Issue by mingleiwang** [plataformatec/faraday-http-cache#77]
I have a question about the code on https://github.com/plataformatec/faraday-http-cache/blob/master/lib/faraday/http_cache.rb#L247. So even if the response is not_modified, this line of code will store the response, right? Would this be extra step since the copy in the cache is still fresh?

**Comment by lucasmazza** [comment]
Because a `304` can update the headers of a stored response in the cache (there is a section in the RFC 7234 about this iirc).
